name: Convert Wiki Links

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'

jobs:
  convert-wiki-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Wichtig: Berechtigungen zum Schreiben von Inhalten hinzufügen
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Debug Info
      run: |
        echo "Repository Contents:"
        ls -la
        echo "Markdown Files:"
        find . -name "*.md" | xargs ls -la
        
    - name: Convert Wiki Links to Markdown Links
      run: |
        node convert-wiki-links.js
        
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "::set-output name=modified::true"
        
    - name: Commit changes
      if: steps.git-check.outputs.modified == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Automatische Konvertierung von Wiki-Links zu Markdown-Links"
        
    - name: Push changes
      if: steps.git-check.outputs.modified == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
